name: PHP build
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    
    - name: Install composer dependencies
      run: composer i
          
    - name: PHP Code Standarts
      run: |
        chmod +x ./bin/phpcs.sh
        ./bin/phpcs.sh
      shell: bash
    
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: "./phpunit.xml"
        version: "9.6"
        php_version: "7.4"
        bootstrap: "./vendor/autoload.php"

    - name: Zip code
      run: |
        chmod 777 ./bin/zip.sh
        ./bin/zip.sh
      shell: bash
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        draft: false
        files: |
          ./build/app.zip
    
