name: PHP build
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install composer dependencies
      run: composer i

    - name: PHP Code Standarts
      run: |
        chmod +x ./bin/phpcs.sh
        ./bin/phpcs.sh
      shell: bash

    - name: Zip code
      run: |
        chmod +x ./bin/zip.sh
        ./bin/zip.sh
      shell: bash
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: false
        files: |
          ./build/app.zip
    
