name: Check pr
run-name: Check pr

on:
  workflow_dispatch
#   pull_request:
#     types: [opened, reopened, synchronize]
#     branches: [ "main", "dev" ]
  
permissions:
  contents: write

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('./composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-
    
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: "./phpunit.xml"
          version: "9.6"
          php_version: "7.4"
          bootstrap: "./vendor/autoload.php"

#   code_standarts:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - uses: php-actions/composer@v6

#       - name: PHP Code Standarts
#         run: |
#           chmod +x ./bin/phpcs.sh
#           ./bin/phpcs.sh
#         shell: bash
