name: Release
run-name: Release

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip code
      run: |
        chmod 777 ./bin/zip.sh
        sudo bash ./bin/zip.sh
      shell: bash
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        draft: false
        files: |
          ./build/app.zip
    
