name: Release
run-name: Release

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip code
      run: |
        chmod 777 ./bin/zip.sh
        sudo bash ./bin/zip.sh
      shell: bash

    - name: "Set COMPOSER_ROOT_VERSION environment variable"
      uses: "ergebnis/composer-root-version-action@main"
      
    - name: "Test variable"
      run: |
        echo ${{COMPOSER_ROOT_VERSION}}
        
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true,
        artifacts: "./build/app.zip"
        tag: "${COMPOSER_ROOT_VERSION}"

    
