name: Release
run-name: Release

on: 
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+dev[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip code
      run: |
        echo "zip it x2"
        chmod 777 ./bin/zip.sh
        sudo bash ./bin/zip.sh
      shell: bash
      
    - uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true,
        artifacts: "./build/app.zip"

    
